version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: financeflowuser
      POSTGRES_PASSWORD: financeflowpass
      POSTGRES_DB: financeflowdb
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '80:80'
    depends_on:
      - postgres
